language: python
python: '3.6'
sudo: false
env:
  global:
  - AWS_DEFAULT_REGION=ap-northeast-1
  - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
install:
- pip install pytest
- pip install -r requirements.txt
script:
- PYTHONPATH=src py.test -vv -r sxX tests
before_deploy:
- make
- mv dist/lambda.zip dist/latest.zip
- cp dist/latest.zip dist/$TRAVIS_COMMIT.zip
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: dB3wk0lbFq9SrH7WC90j+artRsORkUmhqEjmiawkwq9zEl1edoMqp7YHRLYiAcmI+gn8BTtQ5mFh7oXL8coYhAo9J8nssRntDYaSRdPpj65fsfqBpNXiAVAyRi1tL79ySJl6hZvjxTW88XPp0KWJTAXtpNN2KDrp/CGCgYol6GWoxsYBOIzdn6NXZ7RmS9UGa6AFD64HmPzVXSaFsYjdVw1QgXcg/DWh7Txxg2UPz+qWlIBmhkkyWrrQv0CV8EP4BKBNszEl3VhVw7nOmFxLeLMWXfTmXLpyy7m79nbO1EVsAid3C5gwMYm2F8yHOPVEuIrjjFd+nQT6zmVcwqjzS84ccb2xhCG3uinNGdqZquT1LtcsIiwMQSemyI00BvSbYWM6vno8hvDYyc7wIDpnTjBJHOYCFUgN2mZAF7SUgMtFTguBxFGyG4efeRrUOY7htGUrTngTyY5IEEIAqj1aaO/8S1zg/Efb4/i4Hm/EKxI0S0JyiqWAGHDRy4xTkAcK3f1MFT/1IYgCnoOLIJ7gvAntXPeflJqemciwSqE4wdPCdqMPAxVqLM/Rwh7rlMAliPKSd4dXLF/OXoFsvtGC2h2Gcg01DFBWdWVYI8GoUnV4sT7YMww3QOrmhZg/jM89KyCDiHleDoM1Dr/7VBE7bBOqeNeGBMzngaC3GYdXAR4=
  bucket: "$AWS_BUCKET"
  region: "$AWS_BUCKET_REGION"
  local_dir: dist
  upload-dir: lambda/production/connpass2slack
  acl: private
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  email: true
